### ISSUE TITLE
私有化部署，编辑文档功能异常

### ISSUE THREAD

**Issue by Cedric1314** [beeboxcc/eman#1]
<img width="1365" alt="图片" src="https://user-images.githubusercontent.com/42855430/228730860-0917c789-85bd-4a71-a206-2fdd81066bbd.png">
<img width="1055" alt="图片" src="https://user-images.githubusercontent.com/42855430/228730901-2d2f2792-1aa2-4076-bd99-9a89f0278f4b.png">

**Comment by beeboxcc** [comment]
已经发布新版，启用redis
