### ISSUE TITLE
私有化部署遇到问题：missing signature key

### ISSUE THREAD

**Issue by funet8** [beeboxcc/eman#3]
环境：
系统： centos7
Docker version 1.13.1, build 7d71120/1.13.1
Docker Compose version v2.22.0
按照https://hub.docker.com/r/beeboxcc/eman-app执行：

docker-compose up -d
....
报错：
missing signature key
需要key？怎么获取？ 还是需要收费？

**Comment by funet8** [comment]
升级docker版本解决了

**Comment by beeboxcc** [comment]
ok,关闭issue
